- src/App.jsx
- src/ClickMeButton.jsx
- src/CountButton.jsx
- src/CountButtons.jsx
- src/Title.jsx
- src/index.jsx
> Implement simple counter with each component file

- src/App.jsx
- src/Button.jsx
- src/Buttons.jsx
- src/Counter.jsx
- src/index.jsx
Add Counter App
리뷰 부탁드립니다.~
코드를 작성하다가 고민이였던 부분이 컴포넌트에 이벤트로 사용할 props 를 전달할 때 이름을 어떻게 해야될지 모르겠더라구요. 그래서 일단 on 을 접두어로 붙여서 이벤트라는 것을 나타내긴했습니다.
> Add Counter App

- src/app.jsx
- src/button.jsx
- src/buttons.jsx
- src/counter.jsx
- src/index.jsx
- src/page.jsx
1. 컴포넌트 별로 파일 분리
2. 카운터 앱 기능 구현
다음과 같이 작업했습니다.
> [2주차|과제1] Counter 앱 만들고 분리하기 코드 리뷰 부탁드립니다.

- src/App.jsx
- src/Button.jsx
- src/Buttons.jsx
- src/Counter.jsx
- src/Page.jsx
- src/index.jsx
- `Button` 컴포넌트를 만들고 `children` props로 넘어온 버튼 내용 보여주기
- `App` 컴포넌트에서 `useState` hook으로 `count` 상태 관리
- `clickhandler`에 `setCount`로 `count` 변경
- `Button` 컴포넌트로 `clickhandler`넘김
> [week2/assignment1] 과제 리뷰 요청드립니다.

- src/app.jsx
- src/button.jsx
- src/buttons.jsx
- src/counter.jsx
- src/index.jsx
- src/page.jsx
> Simple counter App

- src/App.js
- src/components/button.js
- src/components/buttons.js
- src/components/counter.js
- src/components/page.js
- src/index.jsx
안녕하세요 ㅎㅎ
이번주도 많이 늦었습니다ㅎㅎㅎㅎ
우선 2-1주차 포크한 파일에 강의를 듣고 입력한 index.jsx 내용에서 컴포넌트를 파일분리하는 것을 시도했습니다.
구글에 리액트 파일 분리라고 서칭해서 나오는 내용을 보고 componenet 폴더를 만들고 그 아래에 컴포넌트 파일명을 각각만들고 App.js 에 import 하는 방식으로 시도했습니다. 그런데 index.jsx 에서 함수는 선언되었는데 읽을 수가 없다는 메시지가 확인이 되더라구요ㅠㅠ
> Create counterapp separate files

- src/App.jsx
- src/components/Button.jsx
- src/components/Buttons.jsx
- src/components/Counter.jsx
- src/components/Page.jsx
- src/index.jsx
> Week2_1 simple count app

- src/Components/Button.jsx
- src/Components/Counter.jsx
- src/Components/Page.jsx
- src/index.jsx
- 모든 인수테스트를 통과시켜야 합니다.
- `Click me!`를 클릭하면 숫자가 1씩 증가합니다.
- 숫자 1 버튼을 누르면 숫자가 1씩 증가합니다.
- 숫자 2 버튼을 누르면 숫자가 2씩 증가합니다.
- 숫자 3 버튼을 누르면 숫자가 3씩 증가합니다.
- 숫자 4 버튼을 누르면 숫자가 4씩 증가합니다.
- 숫자 5 버튼을 누르면 숫자가 5씩 증가합니다.
**상태 값**
- count : 클릭 했을 시, 증가 시킬 count 값
**함수**
- handleClickIncreasedNumber(step) : 증가시킬 값인 step을 받아 count 상태값을 증가시키는 함수
- 원래는 Counter 컴포넌트를 생성하여, count 관련 이벤트 함수와 상태값을 관리하는 컴포넌트를 생성하려고 했습니다. 하지만 코드를 작성하다보니, count 상태 값은 모든 버튼과 연관되어 있으니 상위 컴포넌트와 넣어주고, count와 setCount를 하위 컴포넌트로 전달하는 방식으로 작성이 되더군요. 그러다 보니 코드가 뭐가 복잡해지는 느낌을 받았습니다. 그래서 코드가 깔끔해지도록 상위 컴포넌트에 useState와 count 관련 이벤트 함수를 모두 정의 했습니다. 그러다보니 Counter 컴포넌트는 그냥 Button 컴포넌트에 상태값을 전달하는 역할만 해서 그냥 삭제해 버렸습니다.
- 지금은 간단한 코드이기 때문에 상위 컴포넌트에서 관리해야 되는 코드가 적지만, 나중에 되면 상위 컴포넌트에서 관리하는 코드의 량이 많아 질 것 같네요.. 어떻게 해야 이런 문제를 해결해서 좀 더 깔끔하게 코드를 작성할 수 있을까요? 조언 …
> 2강 리액트 - 2주차 과제 1

- src/App.jsx
- src/Button.jsx
- src/ButtonNumbers.jsx
- src/Counter.jsx
- src/NumberButtons.jsx
- src/Page.jsx
- src/index.jsx
Counter 앱 만들고 컴포넌트를 분리하였습니다.
리뷰 요청드립니다.
> [week2] Counter 앱 만들고 파일 분리하기

- src/Button.jsx
- src/Buttons.jsx
- src/Counter.jsx
- src/index.jsx
- if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
- switch는 사용하실 수 없습니다.
- let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
- 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
- indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.
- ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- 모든 인수 테스트를 통과시켜야 합니다.
- 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- 1주차 과제와 강의 영상을 보며 최대한 작은 단위로 작업 단계를 분리하여 작업하려 했습니다. 너무 의도적으로 한 게 아닌가 싶습니다.
- 로직을 담당하는 App 컴포넌트의 클릭 함수가 2개가 있는데  비슷해보여서 통합하여 사용할 수 있지 않을까 생각했습니다.
> [week2-assignment-1] Counter 앱 만들고 파일 분리하기

- src/App.jsx
- src/Button.jsx
- src/Counter.jsx
- src/Page.jsx
- src/index.jsx
- Click me!를 클릭하면 숫자가 1씩 증가합니다.
- 숫자 1 버튼을 누르면 숫자가 1씩 증가합니다.
- 숫자 2 버튼을 누르면 숫자가 2씩 증가합니다.
- 숫자 3 버튼을 누르면 숫자가 3씩 증가합니다.
- 숫자 4 버튼을 누르면 숫자가 4씩 증가합니다.
- 숫자 5 버튼을 누르면 숫자가 5씩 증가합니다.
- if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
- switch는 사용하실 수 없습니다.
- let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
- 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
- indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.
- ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- 모든 인수 테스트를 통과시켜야 합니다.
- 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- 작게 작업을 설계하고, 설계한 작업범위내에서 수행해야 합니다.
- 피드백이 가능한 작업만을 합니다.
> Counter 앱 만들고 파일 분리하기

- package.json
- src/components/App.jsx
- src/components/Button.jsx
- src/components/Buttons.jsx
- src/components/CounterBtn.jsx
- src/components/Page.jsx
- src/index.jsx
**기능**
Click me!를 클릭하면 숫자가 1씩 증가합니다.
숫자 1 버튼을 누르면 숫자가 1씩 증가합니다.
숫자 2 버튼을 누르면 숫자가 2씩 증가합니다.
숫자 3 버튼을 누르면 숫자가 3씩 증가합니다.
숫자 4 버튼을 누르면 숫자가 4씩 증가합니다.
숫자 5 버튼을 누르면 숫자가 5씩 증가합니다.
**제한 조건**
if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
switch는 사용하실 수 없습니다.
let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.
**요구사항**
**진행이슈**
- 자식 컴포넌트에서 부모로 데이터를 보내 어떤 버튼에서 눌렀는지에 따라 count의 state를 바꾸려고 하였고 데이터를 보내는 방법을 찾는 중입니다.
> Count/Divide 과제

- src/App.jsx
- src/Button.jsx
- src/ButtonClickme.jsx
- src/ButtonNumber.jsx
- src/Reducer.jsx
- src/Title.jsx
- src/index.jsx
> Create counter app with react

- src/App.jsx
- src/Button.jsx
- src/Buttons.jsx
- src/Counter.jsx
- src/Page.jsx
- src/index.jsx
- 강의를 들으면서 index.jsx 에 코드를 작성
- 과제대로 파일 하나-컴포넌트 하나로 분리
- 파일 이름은 컴포넌트와 같이 대문자로 시작하는걸로 수정
- 파일 분리 후 어떻게 합쳐야 될지 고민하다가 구글 검색 후 export default 를 써서 객체 내보내기 사용
- 수업과 다르게 과제에서 필요하기에 버튼들에 onClick 등 속성 추가
lint 및 테스트는 통과했지만 얼렁뚱땅 만든감이 없잖아 있어서 풀이 강의 듣고 다시 고쳐보겠습니다..
> 숫자 누를 시 해당 숫자만큼 더해지도록 만들기

- src/App.jsx
- src/Button.jsx
- src/Buttons.jsx
- src/Counter.jsx
- src/Page.jsx
- src/index.jsx
- `click me` 버튼 기능 구현
- `숫자` 버튼 기능 구현
관심사 분리가 조금 생소해서 고민을 많이 했습니다 ㅎㅎㅎㅎ 코드리뷰를 통해 익숙해져보도록 해야겠어요!!..!
> make counter app 

- src/components/App.jsx
- src/components/Button.jsx
- src/components/Buttons.jsx
- src/components/Counter.jsx
- src/components/Page.jsx
- src/index.jsx
PR을 보내고 나서 뒤늦게 함수형 컴포넌트로 하라는 내용을 읽었네요..
그래도 리뷰해주시면 감사하겠습니다.
eslint를 통과하기 위해 PureComponent 를 사용했어요.
react 버전 때문인지, eslint 버전 때문인지 그냥 class X extends Component 는 lint 에러가 나네요..
참고한 곳은 아래입니다.
https://medium.com/groww-engineering/stateless-component-vs-pure-component-d2af88a1200b
여쭤볼 내용이 몇가지 있습니다.
1. 클래스 컴포넌트에 비해 함수형 컴포넌트는 어떤 장점이 있나요??
2. 이런 형태로 component들을 분리하면 되나요? (파일 이름이나 여러모로 지적해주실 부분이 있는지..)
3. index.jsx에서 App component도 파일로 분리하고 ReactDOM.render만 두는 것이 더 이상적인가요?
> 컴포넌트 분리, 간단 카운터

- package-lock.json
- src/App.jsx
- src/Button.jsx
- src/Buttons.jsx
- src/Counter.jsx
- src/Page.jsx
- src/index.jsx
코치님 PR 리뷰 부탁드립니다~~
항상 수고가 많으십니다 ㅎㅎ 
codesoom main 브랜치로 잘못 PR 날려서 다시 요청드립니다 ㅠ
> Seperate every components in each files

- src/App.jsx
- src/Button.jsx
- src/Buttons.jsx
- src/Counter.jsx
- src/Page.jsx
- src/index.jsx
작업기록
- 5' 심플한 화면 그리기
- 5' state로 number 그리기
- 5' handle click, button 리팩토링 - 실패
- button extract를 할 때 값을 어떻게 줘야하는지 까먹었다.
- button extract를 할 때 String 주기, Number를 포함하는 String 주기, function 주기로 나눠서 작업해봐야겠다.
- 5' button extract를 할 때 String만 먼저 줘보기 - 실패
- children에게 주고 있다는 것만 발견
- destructuring 시켰던 것 같은 기억이 난다. 
- children 분리시켜봐야겠다.
- 5' children 찍어보기 - 성공
- props가 어떻게 구성됐었는지, 어떻게 인자 값을 넘기는지 까먹었었구나.
- component에 attribute key,value 주듯이 준다.
- 5' Button component에 handler 넘기기
> Implement counter with React

- .eslintrc.js
- package-lock.json
- package.json
- src/App.jsx
- src/Button.jsx
- src/Buttons.jsx
- src/Page.jsx
- src/index.jsx
> Counter app

- .eslintrc.js
- package-lock.json
- package.json
- src/App.jsx
- src/Buttons.jsx
- src/Counter.jsx
- src/Page.jsx
- src/index.jsx
안녕하세요.
2주차 과제1(카운터앱) 1차 PR 올립니다.
강의를 보고 따라하면 작업  단위를 쪼개서 `commit`을 해보았습니다.
우선, `index.jsx` 와 `App.jsx` 파일을 분리하여 카운터 앱 기능을 완성시켰습니다.
> 2주차 과제1 (카운터 앱 만들기) 

- .eslintrc.js
- package-lock.json
- package.json
- src/components/App.jsx
- src/components/PageMake.jsx
- src/components/buttonFactory.jsx
- src/components/buttonMaker.jsx
- src/components/clickMeButton.jsx
- src/components/firstButtonTest.jsx
- src/index.jsx
제대로 이해하지 못한것 같습니다..검색대로 그냥 쳤네요..
처음 직장다니면서 주중에는 강의만 듣고 문제를 풀지못하였네요..반성하겠습니다.
또, state에 대한 이해가 부족한것 같습니다.
그냥 setState를 count + ints 로 보낼때에는 바로 적용되는데,
처음 생각한 state에 value, count 두개의 값을 넣고 처리하는 방식은 제대로 처리가 안되는데 이부분이 이해가 되지 않는것 같습니다..
> 2주차 첫번째 문제 제출

- .eslintrc.js
- .gitignore
- babel.config.js
- package-lock.json
- src/App.jsx
- src/components/Button.jsx
- src/components/Buttons.jsx
- src/components/Counter.jsx
- src/components/Page.jsx
- src/index.jsx
안녕하세요 트레이너님
늦게 과제를 제출합니다 ㅠㅠ
잘 부탁드립니다 😍
> 과제 1: Counter 앱 만들고 파일 분리하기

- .eslintrc.js
- src/Button.jsx
- src/CounterPage.jsx
- src/index.jsx
> 과제 1 - Counter 앱 만들고 파일 분리하기

- .eslintrc.js
- package-lock.json
- src/App.jsx
- src/Button.jsx
- src/Buttons.jsx
- src/Counter.jsx
- src/Page.jsx
- src/index.jsx
**[ 기능 ]**
Click me!를 클릭하면 숫자가 1씩 증가합니다.
숫자 1 버튼을 누르면 숫자가 1씩 증가합니다.
숫자 2 버튼을 누르면 숫자가 2씩 증가합니다.
숫자 3 버튼을 누르면 숫자가 3씩 증가합니다.
숫자 4 버튼을 누르면 숫자가 4씩 증가합니다.
숫자 5 버튼을 누르면 숫자가 5씩 증가합니다.
**[ 제한 조건 ]**
if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
switch는 사용하실 수 없습니다.
let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.
**[ 요구사항 ]**
> [React 2주차 과제-(1)] Counter 앱 만들고 파일 분리하기

- .eslintrc.js
- babel.config.js
- package-lock.json
- package.json
- src/Button.jsx
- src/Counter.jsx
- src/NumericButtons.jsx
- src/Page.jsx
- src/index.jsx
안녕하세요! 
과제1 counter app 구현하기 제출합니다.
```
function App() { // (1) App컴포넌트: ReactDOM에서 실행됨, count&onClick의 props를 (2)에 넘겨줌
const [count, setCount] = useState(0) //? 강의처럼 풀어서 하는 이유...
function handleClick() {
setCount(count + 1)
}
return (
<div>
<p>Counter</p>
<Counter
count={count}
onClick={handleClick}
/>
<Numeric />
</div>
)
}
```
**App 컴포넌트**
> 질문1) 위와 같이 생긴걸 모두 함수컴포넌트라고 일컫는 것인지 궁금합니다.
> 질문2) 저는 일단 위와 같이 코드를 짰는데... useState 훅에서 강의에선 객체의 형태(?)로 풀어서 작성하시던데.. 이유가 궁금합니다...
```
function Condition({ children }) { // (5) Condition컴포넌트: (4)으로부터 props의 children을 받고, children으로 조건문실행
if (children === 1) {
return (
console.log(children)
)
}
if (children === 2) {
return (
console.log(children)
)
}
}
```
**Condition 컴포넌트**
> 질문1) Button 컴포넌트로부터 children props를 받고, props에 조건문을 적용해서 콘솔창에 띄우는 것 까지는 …
> [2주차 과제1] Counter 앱 만들고 파일 분리하기

- .eslintrc.js
- babel.config.js
- package.json
- src/components/button.jsx
- src/components/buttons.jsx
- src/components/counter.jsx
- src/components/page.jsx
- src/index.jsx
슬랙에 올라온 피드백하신 부분까지 해보았습니다! 
혹시 APP에 포함되어 있는 상태변경용 함수도 분리해야하는걸까요..?
> 2주 과제1 컴포넌트 나누기

- package-lock.json
- package.json
- src/App.jsx
- src/Button.jsx
- src/index.jsx
안녕하세요 2주차 첫번째 과제 제출합니다!
질문이 있습니다!
화면에서 [1, 2, 3, 4, 5] 에 해당하는 영역도 파일을 분리하려다가 말았습니다. 
이유는 파일을 따로 만들어도 재사용 하지 않고 단 하나의 목적 (단순히 버튼들을 감싸는 것)을 위한 파일이 될 것 같아서였습니다.
주 사용되지 않는 경우라도 따로 파일을 분리하는게 맞는걸까요?
> [2주차] 과제 1 - Counter 앱 만들고 파일 분리하기

- babel.config.js
- package-lock.json
- src/App.jsx
- src/Button.jsx
- src/Buttons.jsx
- src/Counter.jsx
- src/Page.jsx
- src/index.jsx
아직 완료하지 못했지만 미리 PR 하고 업데이트하겠습니다.
<hr>
- 숫자 버튼을 생성하는 컴포넌트로 이벤트 핸들러를 전달하였습니다.
- `npm run test:e2e`
- `npm run lint`
> [리액트 7기 표후동] 2주차 과제 1 - Counter 앱 만들고 파일 분리하기

- babel.config.js
- package-lock.json
- package.json
- src/App.jsx
- src/Button.jsx
- src/Buttons.jsx
- src/Counter.jsx
- src/index.jsx
- Counter 앱 만들고 파일 분리하기
이번주도 화이팅!
> [리액트 7기_신현준] 2강 과제 1

- .eslintrc.js
- babel.config.js
- jsconfig.json
- package-lock.json
- src/App.jsx
- src/components/Button.jsx
- src/index.jsx
안녕하세요 리뷰어님~ 이번 과제도 잘 부탁드립니다~
Button 컴포넌트를 별도로 생성하긴 했는데 UI나 다른 기능이 들어가지 않아서 파일 분리의 의미가 크게 느껴지지는 않았던거 같네요.
> [리액트 7기 조윤호] 2주차 과제 1 - Counter 앱 만들고 파일 분리하기 

- babel.config.js
- package-lock.json
- src/components/App.jsx
- src/components/Button.jsx
- src/components/Counter.jsx
- src/components/Title.jsx
- src/index.jsx
Make a counter and separate components.
안녕하세요, 트레이너님!
이번 주도 잘 부탁드립니다!
> Make a counter
